# sgl-omni serve --model-path /home/weights/Qwen/Qwen3-Omni-30B-A3B-Instruct/ --thinker.gpu [2,3] --thinker.tp_size 2 --port 8764 --image_encoder.gpu 0 --talker_ar.engine.disable_cuda_graph on --config examples/configs/qwen3_omni_speech_replica2.yaml

config_cls: Qwen3OmniSpeechPipelineConfig
name: qwen3-omni-speech-replica2
model_path: /home/weights/Qwen/Qwen3-Omni-30B-A3B-Instruct

stages:

  audio_encoder:
    gpu_memory_fraction: 0.1

  image_encoder:
    gpu_memory_fraction: 0.1

processes:
  talker_ar:
    num_replicas: 2
    replica_devices: [4, 5]

  code2wav:
    num_replicas: 2
    replica_devices: [0, 1]
